config/routes.rb
Rails.application.routes.draw do
  get 'flights/index'
  get 'trains/index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'home#main_page'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check
  get 'bus', to: 'home#index'
  get 'show', to: 'home#show'

  get 'train', to: 'trains#index'
  get 'show_train', to: 'trains#show_train'

  get 'flight', to: 'flights#index'
  get 'show_flight', to: 'flights#show_flight'

  get 'allbookings', to: 'allbookings#show'
  get 'history', to: 'allbookings#history'

  # get 'bookings/show_ticket', to:"bookings#show_ticket"
  resources :bookings

  get 'payments/success'
  get 'payments/cancel'
  resources :payments

  # Defines the root path route ("/")-
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  validates :user_id, :date, :mode_type, presence: true

  belongs_to :user
  belongs_to :bookingable, polymorphic: true
  has_many :tickets, dependent: :destroy
  accepts_nested_attributes_for :tickets
end

app/models/bus.rb
class Bus < ApplicationRecord
  validates :name, :total_seets, :departure_time, :arrival_time, :price, :direction_id, :bustype, presence: true

  belongs_to :direction
  has_many :bookings, as: :bookingable
end

app/models/direction.rb
class Direction < ApplicationRecord
  validates :source, :destination, :distance, presence: true

  has_many :buses, dependent: :destroy
  has_many :trains, dependent: :destroy
  has_many :flights, dependent: :destroy
end

app/models/flight.rb
class Flight < ApplicationRecord
  validates :name, :total_seets, :departure_time, :arrival_time, :price, :direction_id, presence: true

  belongs_to :direction
  has_many :bookings, as: :bookingable
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :booking
end

app/models/train.rb
class Train < ApplicationRecord
  validates :name, :total_seets, :departure_time, :arrival_time, :price, :direction_id, :traintype, presence: true

  belongs_to :direction
  has_many :bookings, as: :bookingable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings, dependent: :destroy
end

app/controllers/allbookings_controller.rb
class AllbookingsController < ApplicationController
  def index
  end

  def show
    @bookings = Booking.where(['user_id = ? and date >= ?', params[:user_id], Date.today])
  end

  def history
    @bookings = Booking.where(['user_id = ? and date < ?', params[:user_id], Date.today])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def new
    @booking = Booking.new
    @booking.tickets.build
  end

  def show
    @booking = Booking.find(params[:id])
    @tickets = Ticket.where(booking_id: params[:id])
  end

  def create
    @booking = Booking.new(booking_params)
    last_seat = get_last_seat
    @booking.save
    seat_allocate(last_seat)
    BookingMailer.booking_email(current_user).deliver_later
    redirect_to @booking
  end

  def destroy
    @booking = Booking.find(params[:id])

    manage_cancel_tickets

    @booking.destroy
    redirect_to allbookings_path(user_id: current_user.id)
  end

  private

  def booking_params
    params.require(:booking).permit(:user_id, :date, :mode_type, :bookingable_type, :bookingable_id,
                                    tickets_attributes: %i[name age gender])
  end

  def get_last_seat
    bookingable_type = @booking.bookingable_type
    bookingable_id = @booking.bookingable_id
    last_booking_id = nil

    case bookingable_type
    when 'Bus'
      last_booking = Bus.find(bookingable_id).bookings.last
      last_booking_id = last_booking&.id

    when 'Train'
      last_booking = Train.find(bookingable_id).bookings.last
      last_booking_id = last_booking&.id

    when 'Flight'
      last_booking = Flight.find(bookingable_id).bookings.last
      last_booking_id = last_booking&.id

    end

    if last_booking_id.nil?
      0

    else
      Booking.find(last_booking_id).tickets.last.seat_no
    end
  end

  def seat_allocate(last_seat)
    last_seat = 0 if last_seat.nil?

    tickets = @booking.tickets

    tickets.each do |ticket|
      last_seat += 1
      ticket.update_columns(seat_no: last_seat)
      if @booking.bookingable_type.eql? 'Bus'
        bus = Bus.find(@booking.bookingable_id)
        bus.update_columns(remaning_seats: bus.remaning_seats - 1)

      elsif @booking.bookingable_type.eql? 'Train'
        train = Train.find(@booking.bookingable_id)
        train.update_columns(remaning_seats: train.remaning_seats - 1)

      else
        flight = Flight.find(@booking.bookingable_id)
        flight.update_columns(remaning_seats: flight.remaning_seats - 1)

      end
    end
  end

  def manage_cancel_tickets
    ticket_count = @booking.tickets.count

    if @booking.bookingable_type.eql? 'Bus'
      bus = Bus.find_by(id: @booking.bookingable_id)
      bus.update_columns(remaning_seats: bus.remaning_seats + ticket_count)

    elsif @booking.bookingable_type.eql? 'Train'
      train = Train.find_by(id: @booking.bookingable_id)
      train.update_columns(remaning_seats: train.remaning_seats + ticket_count)

    else
      flight = Flight.find_by(id: @booking.bookingable_id)
      flight.update_columns(remaning_seats: flight.remaning_seats + ticket_count)
    end
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
  end

  def show_flight
    direction_id = Direction.where(source: params[:source], destination: params[:destination]).pluck(:id)
    @flights = Flight.where('direction_id = ?', direction_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def show
    direction_id = Direction.where(source: params[:source], destination: params[:destination]).pluck(:id)
    @buses = Bus.where('direction_id = ?', direction_id)
  end
end

app/controllers/payments_controller.rb
# app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def create
    @amount = 500

    payment_intent = Stripe::PaymentIntent.create({
                                                    amount: @amount,
                                                    currency: 'usd',
                                                    confirmation_method: 'manual',
                                                    confirm: false
                                                  })

    render json: { client_secret: payment_intent.client_secret }
  end

  def confirm
    payment_intent = Stripe::PaymentIntent.retrieve(params[:payment_intent_id])

    payment_intent.confirm({
                             payment_method: params[:payment_method_id]
                           })

    if payment_intent.status == 'requires_action' || payment_intent.status == 'requires_source_action'

      render json: { requires_action: true, client_secret: payment_intent.client_secret }
    else
      render json: { success: true }
    end
  end
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  def index
  end

  def show_train
    direction_id = Direction.where(source: params[:source], destination: params[:destination]).pluck(:id)
    @trains = Train.where('direction_id = ?', direction_id)
  end
end

app/helpers/allbookings_helper.rb
module AllbookingsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/bookingtickets_helper.rb
module BookingticketsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/bookings/_form.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dynamic Forms</title>
</head>
<style>
  .main-container {
    padding: 20px 20px 20px 40px;
  }
  
  .form-container {
    display:flex;
    flex-direction:col;
    padding: 0px 0px 20px 0px;
  }

  .form-group {
    margin-left: 20px;
  }

  .ticket-fields-container {
    margin-bottom: 20px;
    position: relative; 
  }

  .remove-form-btn {
    position: absolute;
    right: 0;
    background-color: #f44336;
    color: white;
    border: none;
    padding: 5px 10px;
    cursor: pointer;
    border-radius:10px;
    margin-top :-8px;
  }

  .remove-form-btn:hover {
    background-color: #d32f2f; 
  }

</style>
<body>
<%= form_with model: @booking, url: bookings_path, method: :post, local: true do |form| %>
  <%= form.hidden_field :user_id, value: current_user.id %>
  <%= form.hidden_field :date, value: params[:date]%>
  <%= form.hidden_field :mode_type, value: params[:bookingable_type] %>
  <%= form.hidden_field :bookingable_type, value: params[:bookingable_type] %>
  <%= form.hidden_field :bookingable_id, value: params[:bookingable_id] %>
  <div class='main-container'>
    <%= form.fields_for :tickets do |f| %> 
      <div class="form-container">
        <div class="form-group">
          <%= f.label :name %> : 
          <%= f.text_field :name, required: true %>
        </div>
        <div class="form-group">
          <%= f.label :age %> : 
          <%= f.number_field :age, required: true %>
        </div>
        <div class="form-group">
          <%= f.label :gender %> : 
          <%= f.radio_button :gender, 'male', required: true %>
          <%= f.label :gender_male, 'Male' %>
          <%= f.radio_button :gender, 'female', required: true %>
          <%= f.label :gender_female, 'Female' %> 
        </div>
      </div>
    <% end %>
    <div id="forms-container">
    </div>
    <div>
      <button type="button" id="add-form-btn"> Add Traveller </button>
      <%= form.submit 'Book Tickets' %>
    </div>
  </div>
<% end %>

<script>
  document.addEventListener('turbo:load', () => {
    const addFormButton = document.getElementById('add-form-btn');
    const formsContainer = document.getElementById('forms-container');
    let formIndex = <%= @booking.tickets.size %>; 
    
    addFormButton.addEventListener('click', () => {
      const newForm = document.createElement('div');
      newForm.className = 'ticket-fields-container';

      newForm.innerHTML = `
        <div class="form-container">
          <div class="form-group">
            <label for="booking_tickets_attributes_${formIndex}_name"> Name : </label>
            <input type="text" name="booking[tickets_attributes][${formIndex}][name]" id="booking_tickets_attributes_${formIndex}_name">
          </div>
          <div class="form-group">
            <label for="booking_tickets_attributes_${formIndex}_age"> Age : </label>
            <input type="number" name="booking[tickets_attributes][${formIndex}][age]" id="booking_tickets_attributes_${formIndex}_age">
          </div>
          <div class="form-group">
            <label> Gender : </label>
            <input type="radio" name="booking[tickets_attributes][${formIndex}][gender]" value="male" id="booking_tickets_attributes_${formIndex}_gender_male">
            <label for="booking_tickets_attributes_${formIndex}_gender_male">Male</label>
            <input type="radio" name="booking[tickets_attributes][${formIndex}][gender]" value="female" id="booking_tickets_attributes_${formIndex}_gender_female">
            <label for="booking_tickets_attributes_${formIndex}_gender_female">Female</label>
          </div>
          <button type="button" class="remove-form-btn">Remove</button>
        </div>
      `;
      formsContainer.appendChild(newForm);
      formIndex++;
    });

    formsContainer.addEventListener('click', (event) => {
      if (event.target.classList.contains('remove-form-btn')) {
        event.target.parentElement.remove();
      }
    });
    
  });
</script>
</body>
</html>

app/views/bookings/_ticket_fields.html.erb
<!-- app/views/bookings/_ticket_fields.html.erb -->
<div class="form-container">
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name ,required: true%>
  </div>
  <div class="form-group">
    <%= f.label :age %>
    <%= f.number_field :age, required: true %>
  </div>
  <div class="form-group">
    <%= f.label :gender %>
    <%= f.radio_button :gender, 'male' ,required: true%>
    <%= f.label :gender_male, 'Male' %>
    <%= f.radio_button :gender, 'female' ,required: true %>
    <%= f.label :gender_female, 'Female' %> 
  </div>
</div>

app/views/bookings/new.html.erb
<% if user_signed_in? %>
  <div>
  </div>
  <%= render :partial => 'form', lacals: {booking: @booking} %>
<% else %>
  <p> Please Sign Up or Sign In to book ticket. </p>
  <h2> <%= link_to "Sign up", new_user_registration_path %>
<% end %>

app/views/bookings/show.html.erb
<html>
    <head>
        <style>
            .main-container{
                padding-top : 20px;
            }
            
            .heading{
                padding-left: 20px;
            }

            .tickets{
                display:flex;
                flex-direction: col;
                flex-wrap:wrap;
            },
            .cards{
                margin:20px;
            }

        </style>
    </head>
    <body>
        <div class='main-container'>
            <div class="heading">
                <p> Booking Id : <%= @booking.id %> </p>
                <p> Booking Date : <%= @booking.date %> </p>
                <p> Type : <%= @booking.mode_type %> </p>
            </div>
            <div class='tickets'>
                <% @tickets.each do |ticket| %>
                <div class="card" style="width: 18rem; margin:20px">
                    <div class="card-header">
                        Ticket
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">Ticket Id : <%= ticket.id %></li>
                        <li class="list-group-item">Name : <%= ticket.name %> </li>
                        <li class="list-group-item">Age : <%= ticket.age %> </li>
                        <li class="list-group-item"> Gender : <%= ticket.gender %> </li>
                    </ul>
                </div>
                <% end %>
            </div>
        </div>
    </body>
</html>

app/views/flights/index.html.erb
<div class="d-flex justify-content-center align-items-center" style="padding-top:100px;">
  <div class="text-center" >
    <h1> Search Your Flights </h1>
    <%= form_with url: "/show_flight", method: :get do |form| %>
    <%= form.text_field :source , placeholder: "Enter your source",required: true %>
    <%= form.text_field :destination , placeholder: "Enter your destination",required: true %>
    <%= form.date_field :date,required: true %>
    <%= form.submit "search" %>
    <% end %>  
  </div>
</div>

app/views/flights/show_flight.html.erb
<html>
  <head>
    <style>
       .not-found{
	  padding-top:100px;
	  margin-left:300px;
	}
    </style>
  </head>
  <body>
		<% if @flights.length === 0 || params[:date].to_date< Date.today() %>
		    <h3 class='not-found'> Oops! Flight route is not avaliable! </h3>
		<% else %>
		<table class="table container">
		<thead>
	  	   <tr>
	    	    <th scope="col"> Number </th>
	    	    <th scope="col"> Flight Name </th>
	    	    <th scope="col"> Total Seats </th>
		    <th scope="col"> Remaning Seats</th>
	    	    <th scope="col"> Departure Time </th>
	    	    <th scope="col"> Arrival Time </th>
	    	    <th scope="col"> Ticket Price </th>
	    	    <th scope="col"> Flight Booking </th>
	  	   </tr>
		</thead>
		    <tbody>	
	  		<% @flights.each do |flight| %>
	    		<tr>
	       		 	<td> <%= flight.id %> </td>
	       		  	<td> <%= flight.name %> </td>
	       		  	<td> <%= flight.total_seets %> </td>
		   	  	<td> <%= flight.remaning_seats %></td>
	       		  	<td> <%= flight.departure_time.to_fs(:time) %> AM </td>
	       		  	<td> <%= flight.arrival_time.to_fs(:time) %> PM </td>
	       		  	<td> <%= flight.price %> </td>
	       		<% if flight.remaning_seats != nil %>
		   	  	<td> <%= link_to "Book Ticket", new_booking_path(bookingable_id: flight.id, bookingable_type: "Flight",date: params[:date]) %> </td>
		   	<% else %>
		   	  	<td> Flight is full </td>
		   	<% end %>
	    		<tr>
	  		<% end %>		
		    </tbody>
		<table>
		<% end %>
	</body>
</html>

app/views/trains/index.html.erb
<div class="d-flex justify-content-center align-items-center" style="padding-top:100px;">
  <div class="text-center" >
    <h1> Search Your Trains </h1>
    <%= form_with url: "/show_train", method: :get do |form| %>
    <%= form.text_field :source , placeholder: "Enter your source" ,required: true%>
    <%= form.text_field :destination , placeholder: "Enter your destination" ,required: true%>
    <%= form.date_field :date ,required: true%>
    <%= form.submit "search" %>
    <% end %>  
  </div>
</div>

app/views/trains/show_train.html.erb
<html>
   <head>
      <style>
	 .not-found{
		padding-top:100px;
		margin-left:300px;
	  }
      </style>
   </head>
   <body>
		<% if @trains.length === 0 || params[:date].to_date< Date.today() %>
			<h3 class='not-found'> Oops! Train route is not avaliable! </h3>
		<% else %>
		<table class="table container">
			<thead>
	  		<tr>
	    		<th scope="col"> Train Number </th>
	    		<th scope="col"> Train Name </th>
	    		<th scope="col"> Total Seats </th>
				<th scope='col'> Remaning Seats </th>
	    		<th scope="col"> Departure Time </th>
	    		<th scope="col"> Arrival Time </th>
	    		<th scope="col"> Train Type </th>
	    		<th scope="col"> Ticket Price </th>
	    		<th scope="col"> Train Booking </th>
	  		</tr>
			</thead>
			<tbody>
	  		<% @trains.each do |train| %>
	    		<tr>
	       			<td> <%= train.id %> </td>
	       			<td> <%= train.name %> </td>
	       			<td> <%= train.total_seets %> </td>
		   			<td> <%= train.remaning_seats %></td>
	       			<td> <%= train.departure_time.to_fs(:time) %> AM</td>
	       			<td> <%= train.arrival_time.to_fs(:time) %> PM</td>
	       			<td> <%= train.traintype %> </td>
	       			<td> <%= train.price %> </td>
		   		<% if train.remaning_seats != nil %>
	       			<td> <%= link_to "Book Ticket", new_booking_path(bookingable_id: train.id, bookingable_type: "Train", date: params[:date]) %> </td>
		   		<% else %>
		    		<td> Train is Full </td>
		   		<% end %>
	    		<tr>
	  		<% end %>
			</tbody>
		<table>
		<% end %>
	</body>
</html>