config/routes.rb
Rails.application.routes.draw do
  get 'flights/index'
  get 'trains/index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'home#main_page'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check
  get 'bus', to: 'home#index'
  get 'show', to: 'home#show'

  get 'train', to: 'trains#index'
  get 'show_train', to: 'trains#show_train'

  get 'flight', to: 'flights#index'
  get 'show_flight', to: 'flights#show_flight'

  get 'allbookings', to: 'allbookings#show'
  get 'history', to: 'allbookings#history'

  # get 'bookings/show_ticket', to:"bookings#show_ticket"
  resources :bookings

  get 'payments/success'
  get 'payments/cancel'
  resources :payments

  # Defines the root path route ("/")-
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  validates :user_id, :date, :mode_type, presence: true

  belongs_to :user
  belongs_to :bookingable, polymorphic: true
  has_many :tickets, dependent: :destroy
  accepts_nested_attributes_for :tickets
end

app/models/bus.rb
class Bus < ApplicationRecord
  validates :name, :total_seets, :departure_time, :arrival_time, :price, :direction_id, :bustype, presence: true

  belongs_to :direction
  has_many :bookings, as: :bookingable
end

app/models/direction.rb
class Direction < ApplicationRecord
  validates :source, :destination, :distance, presence: true

  has_many :buses, dependent: :destroy
  has_many :trains, dependent: :destroy
  has_many :flights, dependent: :destroy
end

app/models/flight.rb
class Flight < ApplicationRecord
  validates :name, :total_seets, :departure_time, :arrival_time, :price, :direction_id, presence: true

  belongs_to :direction
  has_many :bookings, as: :bookingable
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :booking
end

app/models/train.rb
class Train < ApplicationRecord
  validates :name, :total_seets, :departure_time, :arrival_time, :price, :direction_id, :traintype, presence: true

  belongs_to :direction
  has_many :bookings, as: :bookingable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings, dependent: :destroy
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def new
    @booking = Booking.new
    @booking.tickets.build
  end

  def show
    @booking = Booking.find(params[:id])
    @tickets = Ticket.where(booking_id: params[:id])
  end

  def create
    @booking = Booking.new(booking_params)
    last_seat = get_last_seat
    @booking.save
    seat_allocate(last_seat)
    BookingMailer.booking_email(current_user).deliver_later
    redirect_to @booking
  end

  def destroy
    @booking = Booking.find(params[:id])

    manage_cancel_tickets

    @booking.destroy
    redirect_to allbookings_path(user_id: current_user.id)
  end

  private

  def booking_params
    params.require(:booking).permit(:user_id, :date, :mode_type, :bookingable_type, :bookingable_id,
                                    tickets_attributes: %i[name age gender])
  end

  def get_last_seat
    bookingable_type = @booking.bookingable_type
    bookingable_id = @booking.bookingable_id
    last_booking_id = nil

    case bookingable_type
    when 'Bus'
      last_booking = Bus.find(bookingable_id).bookings.last
      last_booking_id = last_booking&.id

    when 'Train'
      last_booking = Train.find(bookingable_id).bookings.last
      last_booking_id = last_booking&.id

    when 'Flight'
      last_booking = Flight.find(bookingable_id).bookings.last
      last_booking_id = last_booking&.id

    end

    if last_booking_id.nil?
      0

    else
      Booking.find(last_booking_id).tickets.last.seat_no
    end
  end

  def seat_allocate(last_seat)
    last_seat = 0 if last_seat.nil?

    tickets = @booking.tickets

    tickets.each do |ticket|
      last_seat += 1
      ticket.update_columns(seat_no: last_seat)
      if @booking.bookingable_type.eql? 'Bus'
        bus = Bus.find(@booking.bookingable_id)
        bus.update_columns(remaning_seats: bus.remaning_seats - 1)

      elsif @booking.bookingable_type.eql? 'Train'
        train = Train.find(@booking.bookingable_id)
        train.update_columns(remaning_seats: train.remaning_seats - 1)

      else
        flight = Flight.find(@booking.bookingable_id)
        flight.update_columns(remaning_seats: flight.remaning_seats - 1)

      end
    end
  end

  def manage_cancel_tickets
    ticket_count = @booking.tickets.count

    if @booking.bookingable_type.eql? 'Bus'
      bus = Bus.find_by(id: @booking.bookingable_id)
      bus.update_columns(remaning_seats: bus.remaning_seats + ticket_count)

    elsif @booking.bookingable_type.eql? 'Train'
      train = Train.find_by(id: @booking.bookingable_id)
      train.update_columns(remaning_seats: train.remaning_seats + ticket_count)

    else
      flight = Flight.find_by(id: @booking.bookingable_id)
      flight.update_columns(remaning_seats: flight.remaning_seats + ticket_count)
    end
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
  end

  def show_flight
    direction_id = Direction.where(source: params[:source], destination: params[:destination]).pluck(:id)
    @flights = Flight.where('direction_id = ?', direction_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def show
    direction_id = Direction.where(source: params[:source], destination: params[:destination]).pluck(:id)
    @buses = Bus.where('direction_id = ?', direction_id)
  end
end

app/controllers/payments_controller.rb
# app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def create
    @amount = 500

    payment_intent = Stripe::PaymentIntent.create({
                                                    amount: @amount,
                                                    currency: 'usd',
                                                    confirmation_method: 'manual',
                                                    confirm: false
                                                  })

    render json: { client_secret: payment_intent.client_secret }
  end

  def confirm
    payment_intent = Stripe::PaymentIntent.retrieve(params[:payment_intent_id])

    payment_intent.confirm({
                             payment_method: params[:payment_method_id]
                           })

    if payment_intent.status == 'requires_action' || payment_intent.status == 'requires_source_action'

      render json: { requires_action: true, client_secret: payment_intent.client_secret }
    else
      render json: { success: true }
    end
  end
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  def index
  end

  def show_train
    direction_id = Direction.where(source: params[:source], destination: params[:destination]).pluck(:id)
    @trains = Train.where('direction_id = ?', direction_id)
  end
end

app/helpers/allbookings_helper.rb
module AllbookingsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/bookingtickets_helper.rb
module BookingticketsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/home/index.html.erb
<html>
  <head>
    
  </head>
  <body>
    <div class="main-container">
      <div class="d-flex justify-content-center align-items-center" style="padding-top:100px;">
      <div class="text-center" >
        <h1> Search Your Buses </h1>
        <%= form_with url: "/show", method: :get do |form| %>
        <%= form.text_field :source , placeholder: "Enter your source", required: true %>
        <%= form.text_field :destination , placeholder: "Enter your destination", required: true %>
        <%= form.date_field :date ,required: true%>
        <%= form.submit "search" %>
        <% end %>  
      </div>
    </div>
    </div>
  </body>
</html>

app/views/home/main_page.html.erb
<div>
<div id="carouselExampleInterval" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active" data-bs-interval="1000">
      <%= image_tag("bus1.jpg", :alt => "rss feed" ,:size => "1300x600") %>
    </div>
    <div class="carousel-item" data-bs-interval="2000">
      <%= image_tag("flight1.jpg", :alt => "rss feed" ,:size => "1300x600") %>
    </div>
    <div class="carousel-item">
      <%= image_tag("train1.jpg", :alt => "rss feed" ,:size => "1300x600") %>
    </div>
    <div class="carousel-item active" data-bs-interval="10000">
      <%= image_tag("bus1.jpg", :alt => "rss feed" ,:size => "1300x600") %>
    </div>  
    <div class="carousel-item" data-bs-interval="2000">
      <%= image_tag("flight2.jpg", :alt => "rss feed" ,:size => "1300x600") %>
    </div>
    <div class="carousel-item">
      <%= image_tag("train2.jpg", :alt => "rss feed" ,:size => "1300x600") %>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
<h2 class='text-center my-4'>Get Some Offers</h2>
<div class="row row-cols-1 row-cols-md-2 g-4 my-4">
  <div class="col w-25">
    <div class="card">
      <%= image_tag("bus1.jpg", :alt => "rss feed") %>
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
    </div>
  </div>
  <div class="col w-25">
    <div class="card">
      <%= image_tag("bus2.jpg", :alt => "rss feed" ) %>
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
    </div>
  </div>
  <div class="col w-25">
    <div class="card">
      <%= image_tag("bus3.jpg", :alt => "rss feed" ) %>
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content.</p>
      </div>
    </div>
  </div>
  <div class="col w-25">
    <div class="card">
      <%= image_tag("train1.jpg", :alt => "rss feed") %>
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
    </div>
  </div>
  <div class="col w-25">
    <div class="card">
      <%= image_tag("train2.jpg", :alt => "rss feed") %>
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
    </div>
  </div>
  <div class="col w-25">
    <div class="card">
      <%= image_tag("train3.jpg", :alt => "rss feed" ) %>
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
    </div>
  </div>
  <div class="col w-25">
    <div class="card">
      <%= image_tag("flight1.jpg", :alt => "rss feed" ) %>
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content.</p>
      </div>
    </div>
  </div>
  <div class="col w-25">
    <div class="card">
      <%= image_tag("flight2.jpg", :alt => "rss feed") %>
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
    </div>
  </div>
</div>
</div>
<%= render :partial => 'comman/footer' %>

app/views/home/root_page.html.erb
<div>
<div id="carouselExampleInterval" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active" data-bs-interval="1000">
      <%= image_tag("bus1.jpg", :alt => "rss feed" ,:size => "1300x600") %>
    </div>
    <div class="carousel-item" data-bs-interval="2000">
      <%= image_tag("flight1.jpg", :alt => "rss feed" ,:size => "1300x600") %>
    </div>
    <div class="carousel-item">
      <%= image_tag("train1.jpg", :alt => "rss feed" ,:size => "1300x600") %>
    </div>
    <div class="carousel-item active" data-bs-interval="10000">
      <%= image_tag("bus1.jpg", :alt => "rss feed" ,:size => "1300x600") %>
    </div>  
    <div class="carousel-item" data-bs-interval="2000">
      <%= image_tag("flight2.jpg", :alt => "rss feed" ,:size => "1300x600") %>
    </div>
    <div class="carousel-item">
      <%= image_tag("train2.jpg", :alt => "rss feed" ,:size => "1300x600") %>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
<h2 class='text-center my-4'>Get Some Offers</h2>
<div class="row row-cols-1 row-cols-md-2 g-4 my-4">
  <div class="col w-25">
    <div class="card">
      <%= image_tag("bus1.jpg", :alt => "rss feed") %>
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
    </div>
  </div>
  <div class="col w-25">
    <div class="card">
      <%= image_tag("bus2.jpg", :alt => "rss feed" ) %>
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
    </div>
  </div>
  <div class="col w-25">
    <div class="card">
      <%= image_tag("bus3.jpg", :alt => "rss feed" ) %>
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content.</p>
      </div>
    </div>
  </div>
  <div class="col w-25">
    <div class="card">
      <%= image_tag("train1.jpg", :alt => "rss feed") %>
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
    </div>
  </div>
   <div class="col w-25">
    <div class="card">
      <%= image_tag("train2.jpg", :alt => "rss feed") %>
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
    </div>
  </div>
  <div class="col w-25">
    <div class="card">
      <%= image_tag("train3.jpg", :alt => "rss feed" ) %>
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
    </div>
  </div>
  <div class="col w-25">
    <div class="card">
      <%= image_tag("flight1.jpg", :alt => "rss feed" ) %>
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content.</p>
      </div>
    </div>
  </div>
  <div class="col w-25">
    <div class="card">
      <%= image_tag("flight2.jpg", :alt => "rss feed") %>
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
    </div>
  </div>
</div>
</div>
<%= render :partial => 'comman/footer' %>

app/views/home/rootpage.html.erb
<div>
<div id="carouselExampleInterval" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active" data-bs-interval="1000">
      <%= image_tag("bus1.jpg", :alt => "rss feed" ,:size => "1300x600") %>
    </div>
    <div class="carousel-item" data-bs-interval="2000">
      <%= image_tag("flight1.jpg", :alt => "rss feed" ,:size => "1300x600") %>
    </div>
    <div class="carousel-item">
      <%= image_tag("train1.jpg", :alt => "rss feed" ,:size => "1300x600") %>
    </div>
    <div class="carousel-item active" data-bs-interval="10000">
      <%= image_tag("bus1.jpg", :alt => "rss feed" ,:size => "1300x600") %>
    </div>  
    <div class="carousel-item" data-bs-interval="2000">
      <%= image_tag("flight2.jpg", :alt => "rss feed" ,:size => "1300x600") %>
    </div>
    <div class="carousel-item">
      <%= image_tag("train2.jpg", :alt => "rss feed" ,:size => "1300x600") %>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
<h2 class='text-center my-4'>Get Some Offers</h2>
<div class="row row-cols-1 row-cols-md-2 g-4 my-4">
  <div class="col w-25">
    <div class="card">
      <%= image_tag("bus1.jpg", :alt => "rss feed") %>
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
    </div>
  </div>
  <div class="col w-25">
    <div class="card">
      <%= image_tag("bus2.jpg", :alt => "rss feed" ) %>
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
    </div>
  </div>
  <div class="col w-25">
    <div class="card">
      <%= image_tag("bus3.jpg", :alt => "rss feed" ) %>
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content.</p>
      </div>
    </div>
  </div>
  <div class="col w-25">
    <div class="card">
      <%= image_tag("train1.jpg", :alt => "rss feed") %>
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
    </div>
  </div>
   <div class="col w-25">
    <div class="card">
      <%= image_tag("train2.jpg", :alt => "rss feed") %>
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
    </div>
  </div>
  <div class="col w-25">
    <div class="card">
      <%= image_tag("train3.jpg", :alt => "rss feed" ) %>
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
    </div>
  </div>
  <div class="col w-25">
    <div class="card">
      <%= image_tag("flight1.jpg", :alt => "rss feed" ) %>
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content.</p>
      </div>
    </div>
  </div>
  <div class="col w-25">
    <div class="card">
      <%= image_tag("flight2.jpg", :alt => "rss feed") %>
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
    </div>
  </div>
</div>
</div>
<%= render :partial => 'comman/footer' %>

app/views/home/show.html.erb
<html>
   <head>
      <style>
	 	.not-found{
	      padding-top:100px;
	      margin-left:300px;
	  	}
      </style>
   </head>
   <body>
		<% if @buses.length === 0 || params[:date].to_date< Date.today() %>
			<h3 class='not-found'> Oops! Bus route is not avaliable! </h3>
		<% else %>
		<table class="table container">
		   <thead>
	  			<tr>
	    		  <th scope="col"> Bus Number </th>
	    		  <th scope="col"> Bus Name </th>
	    		  <th scope="col"> Total Seats </th>
			  	  <th scope="col"> Remaning seats </th>
	    		  <th scope="col"> Departure Time </th>
	    		  <th scope="col"> Arrival Time </th>
	    		  <th scope="col"> Ticket Price </th>
	    		  <th scope="col"> Bus Booking </th>
	  			</tr>
		   </thead>
		   <tbody>
	  		<% @buses.each do |bus| %>
	    		<tr>
	       		   <td> <%= bus.id %> </td>
	       		   <td> <%= bus.name %> </td>
	       		   <td> <%= bus.total_seets %> </td>
		   	   	   <td> <%= bus.remaning_seats %> </td>
	       		   <td> <%= bus.departure_time.to_fs(:time) %> AM</td>
	       		   <td> <%= bus.arrival_time.to_fs(:time) %> PM</td>
	       		   <td> <%= bus.price %> </td>
		   		<% if bus.remaning_seats != nil %>
	       		   <td> <%= link_to "Book Ticket", new_booking_path(bookingable_id: bus.id,bookingable_type: "Bus", date: params[:date]) %> </td>
		   		<% else %>
		   	   	   <td> Bus is Full </td>
		   		<% end %>
	    		<tr>
	  		<% end %>
		    </tbody>
		<table>
		<% end %>
	</body>
</html>

app/views/payments/index.html.erb
<%= button_to 'make payment',payments_path ,method: :post %>