config/routes.rb
Rails.application.routes.draw do
  get 'flights/index'
  get 'trains/index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'home#main_page'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check
  get 'bus', to: 'home#index'
  get 'show', to: 'home#show'

  get 'train', to: 'trains#index'
  get 'show_train', to: 'trains#show_train'

  get 'flight', to: 'flights#index'
  get 'show_flight', to: 'flights#show_flight'

  get 'allbookings', to: 'allbookings#show'
  get 'history', to: 'allbookings#history'

  # get 'bookings/show_ticket', to:"bookings#show_ticket"
  resources :bookings

  get 'payments/success'
  get 'payments/cancel'
  resources :payments

  # Defines the root path route ("/")-
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  validates :user_id, :date, :mode_type, presence: true

  belongs_to :user
  belongs_to :bookingable, polymorphic: true
  has_many :tickets, dependent: :destroy
  accepts_nested_attributes_for :tickets
end

app/models/bus.rb
class Bus < ApplicationRecord
  validates :name, :total_seets, :departure_time, :arrival_time, :price, :direction_id, :bustype, presence: true

  belongs_to :direction
  has_many :bookings, as: :bookingable
end

app/models/direction.rb
class Direction < ApplicationRecord
  validates :source, :destination, :distance, presence: true

  has_many :buses, dependent: :destroy
  has_many :trains, dependent: :destroy
  has_many :flights, dependent: :destroy
end

app/models/flight.rb
class Flight < ApplicationRecord
  validates :name, :total_seets, :departure_time, :arrival_time, :price, :direction_id, presence: true

  belongs_to :direction
  has_many :bookings, as: :bookingable
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :booking
end

app/models/train.rb
class Train < ApplicationRecord
  validates :name, :total_seets, :departure_time, :arrival_time, :price, :direction_id, :traintype, presence: true

  belongs_to :direction
  has_many :bookings, as: :bookingable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings, dependent: :destroy
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
  end

  def show_flight
    direction_id = Direction.where(source: params[:source], destination: params[:destination]).pluck(:id)
    @flights = Flight.where('direction_id = ?', direction_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def show
    direction_id = Direction.where(source: params[:source], destination: params[:destination]).pluck(:id)
    @buses = Bus.where('direction_id = ?', direction_id)
  end
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  def index
  end

  def show_train
    direction_id = Direction.where(source: params[:source], destination: params[:destination]).pluck(:id)
    @trains = Train.where('direction_id = ?', direction_id)
  end
end

app/helpers/allbookings_helper.rb
module AllbookingsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/bookingtickets_helper.rb
module BookingticketsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/comman/_footer.html.erb
<!-- Remove the container if you want to extend the Footer to full width. -->
<div class="container my-5">

  <footer style="bg-light">
    <div class="container p-4">
      <div class="row">
        <div class="col-lg-3 col-md-6 mb-4">
          <h5 class="mb-3" style="letter-spacing: 2px; color: #7f4722;">Booking online</h5>
          <ul class="list-unstyled mb-0">
            <li class="mb-1">
              <a href="#!" style="color: #4f4f4f;">frequently asked questions</a>
            </li>
            <li class="mb-1">
              <a href="#!" style="color: #4f4f4f;">delivery</a>
            </li>
            <li class="mb-1">
              <a href="#!" style="color: #4f4f4f;">pricing</a>
            </li>
            <li>
              <a href="#!" style="color: #4f4f4f;">where we deliver?</a>
            </li>
          </ul>
        </div>
        <div class="col-lg-3 col-md-6 mb-4">
          <h5 class="mb-3" style="letter-spacing: 2px; color: #7f4722;">git cards</h5>
          <ul class="list-unstyled mb-0">
            <li class="mb-1">
              <a href="#!" style="color: #4f4f4f;">frequently asked questions</a>
            </li>
            <li class="mb-1">
              <a href="#!" style="color: #4f4f4f;">delivery and payment</a>
            </li>
            <li class="mb-1">
              <a href="#!" style="color: #4f4f4f;">activate the card</a>
            </li>
            <li>
              <a href="#!" style="color: #4f4f4f;">rules</a>
            </li>
          </ul>
        </div>
        <div class="col-lg-3 col-md-6 mb-4">
          <h5 class="mb-3" style="letter-spacing: 2px; color: #7f4722;">Travelles</h5>
          <ul class="list-unstyled mb-0">
            <li class="mb-1">
              <a href="#!" style="color: #4f4f4f;">buy a gift card</a>
            </li>
            <li class="mb-1">
              <a href="#!" style="color: #4f4f4f;">history</a>
            </li>
            <li class="mb-1">
              <a href="#!" style="color: #4f4f4f;">return</a>
            </li>
            <li>
              <a href="#!" style="color: #4f4f4f;">contact</a>
            </li>
          </ul>
        </div>
        <div class="col-lg-3 col-md-6 mb-4">
          <h5 class="mb-3" style="letter-spacing: 2px; color: #7f4722;">diamond club</h5>
          <ul class="list-unstyled mb-0">
            <li class="mb-1">
              <a href="#!" style="color: #4f4f4f;">registration</a>
            </li>
            <li class="mb-1">
              <a href="#!" style="color: #4f4f4f;">application</a>
            </li>
            <li class="mb-1">
              <a href="#!" style="color: #4f4f4f;">about program</a>
            </li>
            <li>
              <a href="#!" style="color: #4f4f4f;">rules</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2024 Copyright:
      <a class="text-dark" href="https://mdbootstrap.com/">ticketbookingapp.com</a>
    </div>
    <!-- Copyright -->
  </footer>

</div>
<!-- End of .container -->

app/views/comman/_nav.html.erb
<html>
  <head>
    <style>
      .logo{
        color:black;
        font-family: "Times New Roman", Times, serif;
        margin-left:10px; 
        font-weight: bold;
        font-size: 25px;
        text-decoration:none
      },
      
    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light" style="background:#a6a6a6;">
      <%= link_to "Ticket Booking", root_path ,class:"logo" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

    <div class="d-flex justify-content-between collapse navbar-collapse" id="navbarSupportedContent">
      <div class='d-flex w-50 justify-content-around'>
        <div>
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <%= link_to "Bus", bus_path, class:"nav-link" %>
            </li>
          </ul>
        </div>
        <div>
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <%= link_to "Train", trains_index_path ,class:"nav-link" %>
            </li>
          </ul>
        </div>
        <div>
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <%= link_to "Flight", flights_index_path, class:"nav-link" %>
            </li>
          </ul>
        </div>
        <% if user_signed_in? %>
          <div>
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <%= link_to "Your Bookings", allbookings_path(user_id:current_user.id) ,class:"nav-link"%>
              </li>
            </ul>
          </div>
            <div>
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <%= link_to "History", history_path(user_id:current_user.id) ,class:"nav-link"%>
              </li>
            </ul>
          </div>
        <% end %>
    </div>
    <div class="d-flex flex-row mx-4">
      <% if user_signed_in? %> 
        <div class='mx-4'> Welcome <%= current_user.email %> </div> 
        <%= button_to "Sign out", destroy_user_session_path, method: :delete %> 
      <% else %>
        <%= button_to "Sign in", new_user_session_path %> 
      <% end %>
    </div>
    </form>
    </div>
    </nav>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ticketbookingsystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>

    <style>
      .main-container{
        height:100vh;
        background:#e6e6e6;
      }
    </style>
  </head>
  <body class='container'>
    <%= render 'comman/nav' %>
    <div class="main-container">
      <%= yield %>
    </div>
  </body>
</html>