config/routes.rb
Rails.application.routes.draw do
  get 'flights/index'
  get 'trains/index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'home#main_page'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check
  get 'bus', to: 'home#index'
  get 'show', to: 'home#show'

  get 'train', to: 'trains#index'
  get 'show_train', to: 'trains#show_train'

  get 'flight', to: 'flights#index'
  get 'show_flight', to: 'flights#show_flight'

  get 'allbookings', to: 'allbookings#show'
  get 'history', to: 'allbookings#history'

  # get 'bookings/show_ticket', to:"bookings#show_ticket"
  resources :bookings

  get 'payments/success'
  get 'payments/cancel'
  resources :payments

  # Defines the root path route ("/")-
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  validates :user_id, :date, :mode_type, presence: true

  belongs_to :user
  belongs_to :bookingable, polymorphic: true
  has_many :tickets, dependent: :destroy
  accepts_nested_attributes_for :tickets
end

app/models/bus.rb
class Bus < ApplicationRecord
  validates :name, :total_seets, :departure_time, :arrival_time, :price, :direction_id, :bustype, presence: true

  belongs_to :direction
  has_many :bookings, as: :bookingable
end

app/models/direction.rb
class Direction < ApplicationRecord
  validates :source, :destination, :distance, presence: true

  has_many :buses, dependent: :destroy
  has_many :trains, dependent: :destroy
  has_many :flights, dependent: :destroy
end

app/models/flight.rb
class Flight < ApplicationRecord
  validates :name, :total_seets, :departure_time, :arrival_time, :price, :direction_id, presence: true

  belongs_to :direction
  has_many :bookings, as: :bookingable
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :booking
end

app/models/train.rb
class Train < ApplicationRecord
  validates :name, :total_seets, :departure_time, :arrival_time, :price, :direction_id, :traintype, presence: true

  belongs_to :direction
  has_many :bookings, as: :bookingable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings, dependent: :destroy
end

app/controllers/allbookings_controller.rb
class AllbookingsController < ApplicationController
  def index
  end

  def show
    @bookings = Booking.where(['user_id = ? and date >= ?', params[:user_id], Date.today])
  end

  def history
    @bookings = Booking.where(['user_id = ? and date < ?', params[:user_id], Date.today])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def new
    @booking = Booking.new
    @booking.tickets.build
  end

  def show
    @booking = Booking.find(params[:id])
    @tickets = Ticket.where(booking_id: params[:id])
  end

  def create
    @booking = Booking.new(booking_params)
    last_seat = get_last_seat
    @booking.save
    seat_allocate(last_seat)
    BookingMailer.booking_email(current_user).deliver_later
    redirect_to @booking
  end

  def destroy
    @booking = Booking.find(params[:id])

    manage_cancel_tickets

    @booking.destroy
    redirect_to allbookings_path(user_id: current_user.id)
  end

  private

  def booking_params
    params.require(:booking).permit(:user_id, :date, :mode_type, :bookingable_type, :bookingable_id,
                                    tickets_attributes: %i[name age gender])
  end

  def get_last_seat
    bookingable_type = @booking.bookingable_type
    bookingable_id = @booking.bookingable_id
    last_booking_id = nil

    case bookingable_type
    when 'Bus'
      last_booking = Bus.find(bookingable_id).bookings.last
      last_booking_id = last_booking&.id

    when 'Train'
      last_booking = Train.find(bookingable_id).bookings.last
      last_booking_id = last_booking&.id

    when 'Flight'
      last_booking = Flight.find(bookingable_id).bookings.last
      last_booking_id = last_booking&.id

    end

    if last_booking_id.nil?
      0

    else
      Booking.find(last_booking_id).tickets.last.seat_no
    end
  end

  def seat_allocate(last_seat)
    last_seat = 0 if last_seat.nil?

    tickets = @booking.tickets

    tickets.each do |ticket|
      last_seat += 1
      ticket.update_columns(seat_no: last_seat)
      if @booking.bookingable_type.eql? 'Bus'
        bus = Bus.find(@booking.bookingable_id)
        bus.update_columns(remaning_seats: bus.remaning_seats - 1)

      elsif @booking.bookingable_type.eql? 'Train'
        train = Train.find(@booking.bookingable_id)
        train.update_columns(remaning_seats: train.remaning_seats - 1)

      else
        flight = Flight.find(@booking.bookingable_id)
        flight.update_columns(remaning_seats: flight.remaning_seats - 1)

      end
    end
  end

  def manage_cancel_tickets
    ticket_count = @booking.tickets.count

    if @booking.bookingable_type.eql? 'Bus'
      bus = Bus.find_by(id: @booking.bookingable_id)
      bus.update_columns(remaning_seats: bus.remaning_seats + ticket_count)

    elsif @booking.bookingable_type.eql? 'Train'
      train = Train.find_by(id: @booking.bookingable_id)
      train.update_columns(remaning_seats: train.remaning_seats + ticket_count)

    else
      flight = Flight.find_by(id: @booking.bookingable_id)
      flight.update_columns(remaning_seats: flight.remaning_seats + ticket_count)
    end
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
  end

  def show_flight
    direction_id = Direction.where(source: params[:source], destination: params[:destination]).pluck(:id)
    @flights = Flight.where('direction_id = ?', direction_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def show
    direction_id = Direction.where(source: params[:source], destination: params[:destination]).pluck(:id)
    @buses = Bus.where('direction_id = ?', direction_id)
  end
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  def index
  end

  def show_train
    direction_id = Direction.where(source: params[:source], destination: params[:destination]).pluck(:id)
    @trains = Train.where('direction_id = ?', direction_id)
  end
end

app/helpers/allbookings_helper.rb
module AllbookingsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/bookingtickets_helper.rb
module BookingticketsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/allbookings/history.html.erb
<html>
  <head>
   <style>
     .not-found{
	      padding-top:100px;
	      margin-left:150px;
      }
    </style>
  </head>
  <body>
    <%if @bookings.length === 0 %>
      <h1 class='not-found'>You are not having any previous bookings! </h1>
    <% else %>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col"> Booking id </th>
          <th scope="col"> Date </th>
          <th scope="col"> Type </th>
          <th scope="col"> Tickets </th>
        </tr>
      </thead>
      <tbody>
        <% @bookings.each do |booking| %>
          <tr>
            <th scope="row"> <%= booking.id %> </th>
            <td> <%= booking.date %> </td>
            <td> <%= booking.mode_type %> </td>
            <td>
              <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modal-<%= booking.id %>" >
                see tickets
              </button>
                <div class="modal fade" id="modal-<%= booking.id %>" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="staticBackdropLabel">All Tickets</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body">
                        <%= booking.bookingable_type %> Name : <%= booking.bookingable.name %> <br>
                          Departure Time : <%= booking.bookingable.departure_time.to_fs( :time ) %> AM <br>
                          Arrival Time :  <%= booking.bookingable.arrival_time.to_fs( :time ) %> PM <br>
                          Price : <%= booking.bookingable.price%> Rs<br>
                          Source : <%= booking.bookingable.direction.source %><br>
                          Destination : <%= booking.bookingable.direction.destination %><br>
                          Distance : <%= booking.bookingable.direction.distance %> Km<br><br>
                        <% booking.tickets.each do |ticket| %>
                          Ticket Id : <%= ticket.id %><br>
                          Seat No : <%= ticket.seat_no %><br>
                          Name : <%= ticket.name %><br>
                          Gender : <%= ticket.gender %> 
                          <br><br>
                        <% end %> 
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                      </div>
                    </div>
                  </div>
                </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <% end %>
  </body>
</html>

app/views/allbookings/show.html.erb
<html>
  <head>
   <style>
     .not-found{
	      padding-top:100px;
	      margin-left:300px;
      }
    </style>
  </head>
  <body>
    <%if @bookings.length === 0 %>
      <h1 class='not-found'>Please First Book your Joruny! </h1>
    <% else %>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col"> Booking id </th>
          <th scope="col"> Date </th>
          <th scope="col"> Type </th>
          <th scope="col"> Tickets </th>
          <th scope="col"> Cancel Bookings </th>
        </tr>
      </thead>
      <tbody>
        <% @bookings.each do |booking| %>
          <tr>
            <th scope="row"> <%= booking.id %> </th>
            <td> <%= booking.date %> </td>
            <td> <%= booking.mode_type %> </td>
            <td>
              <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modal-<%= booking.id %>" >
                see tickets
              </button>
                <div class="modal fade" id="modal-<%= booking.id %>" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="staticBackdropLabel">All Tickets</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body">
                        <%= booking.bookingable_type %> Name : <%= booking.bookingable.name %> <br>
                          Departure Time : <%= booking.bookingable.departure_time.to_fs( :time ) %> AM <br>
                          Arrival Time :  <%= booking.bookingable.arrival_time.to_fs( :time ) %> PM <br>
                          Price : <%= booking.bookingable.price%> Rs<br>
                          Source : <%= booking.bookingable.direction.source %><br>
                          Destination : <%= booking.bookingable.direction.destination %><br>
                          Distance : <%= booking.bookingable.direction.distance %> Km<br><br>
                        <% booking.tickets.each do |ticket| %>
                          Ticket Id : <%= ticket.id %><br>
                          Seat No : <%= ticket.seat_no %><br>
                          Name : <%= ticket.name %><br>
                          Gender : <%= ticket.gender %>
                          <br><br>
                        <% end %> 
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                      </div>
                    </div>
                  </div>
                </div>
            </td>
            <td>
              <%= button_to "Cancel Booking", booking_path(booking) ,method: :delete, data: {turbo_confirm: "Are you sure?"}, class:'btn btn-danger'%>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <% end %>
  </body>
</html>

 